import NavbarComponent from "@/components/NavbarComponent";
import "../globals.css";
import SidebarComponent from "@/components/SidebarComponent";
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="font-SFProDisplay">
                <div className="flex">
                    <SidebarComponent className={`!w-[20vw]`} />
                    <div className="w-[80vw]">
                        <NavbarComponent className={`!w-[80vw]`} />
                        <div className="p-6">
                            {children}
                        </div>
                    </div>
                </div>
            </body>
        </html >
    );
}
