
import { Provider } from "@/components/Provider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-SFProDisplay">
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
